### ISSUE TITLE
possibility to start video via JS func?

### ISSUE THREAD

**Issue by toccamonium-fe** [lygie2221/embettyvideo4typo3#3]
Hi, thx for plugin. Is there a way to tigger the play button via JS instead of clicking on it?

**Comment by lygie2221** [comment]
I am not absolutely sure if this works with all browsers. I tested it in Chrome and Firefox and it seems to work:

`document.querySelector('embetty-video').shadowRoot.querySelector('#playbutton').click();`

**Comment by toccamonium-fe** [comment]
great, works, thx!
