### ISSUE TITLE
extension update for version 11?

### ISSUE THREAD

**Issue by toccamonium-fe** [lygie2221/embettyvideo4typo3#4]
Hi Tobias, thanks for you useful extension. Are there any plans to upgrade it to version 11 soon?

**Comment by lygie2221** [comment]
Hi,
thank you for your feedback and for reminding me on version 11. I will try to release an upgrades version within the next days or weeks.

**Comment by lygie2221** [comment]
I pushed a new version to github and TER 
https://extensions.typo3.org/extension/embettyvideo4typo3
It seem to work fine on one of my development websites using TYPO3 11.5.13
