### ISSUE TITLE
Support for Vimeo

### ISSUE THREAD

**Issue by wowaTYPO3** [lygie2221/embettyvideo4typo3#5]
It would be great if you could also embed videos from Vimeo. Then I would use the extension immediately :)

**Comment by lygie2221** [comment]
Hi there,

I will try to find the time to add a template for vimeo and a switch in the backend that let you choose your platform.
Meanwhile, you can simply put the Vimeo ID in the field in the backend and than override the template

Resources/Private/Templates/Video/Show.html

changing type="youtube" into type="vimeo" in the lines 8 and 12, and you should be fine.

**Comment by lygie2221** [comment]
I have added support for vimeo
